### ISSUE TITLE
FR: support clockwise rotation or both

### ISSUE THREAD

**Issue by indiscipline** [indiscipline/tetronimia#6]
**Option 1:**
Supporting both rotation directions can be easily implemented, however, this:
1. Requires one additional key to be used
2. Adds additional balance variation to the game (if you wanted to undo the rotation, you would do it in 1 keypress, not 3), and I'd like to minimize the number of them as much as possible

**Option 2:**
Support only one rotation direction but add the direction as an option.
This is even easier and:
1. Doesn't change the controls
2. Doesn't break the balance, as rotating in the other direction can be considered a rotation in the original direction on a fully mirrored game field (all the figures are either symmetric or have their symmetric counterparts).
3. Satisfies some potential user preferences

So I'm all for the option 2, but we need user feedback. You can "vote" with thumbs-up reactions under the next two comments.

**Comment by indiscipline** [comment]
To vote for **Option 1** "Support both rotation directions during the game" leave a thumbs-up reaction under this comment.

**Comment by indiscipline** [comment]
To vote for **Option 2** "Support switching rotation directions as a game option" leave a thumbs-up reaction under this comment.

**Comment by kaushalmodi** [comment]
> Support both rotation directions during the game

How about KEY for rotation in one direction and SHIFT+KEY for rotation in another.

**Comment by indiscipline** [comment]
> How about KEY for rotation in one direction and SHIFT+KEY for rotation in another.
That's a viable option, however, what matters is not the specific key combo, but whether we add a mode for it or not at all. If we have some key combination which expands the available moves, it should depend on some game option, otherwise we invalidate the replayability.

It looks like at least 3 people want it, but I'd like to wait a bit more before moving on with this. I'm set on leaving only 1 rotation direction as the default though, at least for now.

**Comment by indiscipline** [comment]
Went with the path of least resistance and implemented Option 2 in commit 5136c7ce1b274d70278aae48abf851a4c11cd602 as a partial fulfillment of this FR.

Now Tetronimia supports setting the rotation direction via `-r` / `--rotation` switch. Possible values: `ccw` and `cw`. The default is still counterclockwise.

**Comment by indiscipline** [comment]
Well, we have a *poll*, not a *vote*, here...
